name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Lane4 DotEnv : Run Build, QA Tools and Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klonen
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker Compose Setup: Container bauen
      - name: Build Docker Container
        run: make build

      # 3. Installiere Composer-Abhängigkeiten
      - name: Install dependencies
        run: make install

      # 4. Statische Codeanalyse ausführen
      - name: Run PHPStan (Static Analysis)
        run: make phpstan

      # 5. Überprüfe Coding Standards (PHP_CodeSniffer)
      - name: Check Code Standards with PHPCS
        run: make phpcs

      # 6. PHPUnit Tests starten
      - name: Run PHPUnit Tests
        run: make phpunit

      # 7. PHPUnit Tests mit Coverage starten
      - name: Run PHPUnit Tests with Coverage
        run: make phpunit-coverage

      # 8. Docker Umgebung herunterfahren, falls erforderlich
      - name: Tear Down Docker Environment
        if: always()
        run: make remove
