name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Lane4 DotEnv - Run Build, QA Tools and Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klonen
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker login
      - name: Login to docker
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

      # 3. Docker image pull
      - name: Login to docker
        run: docker pull lane4digital/lane4-php-cli:latest

      # 4. Installiere Composer-Abhängigkeiten
      - name: Install dependencies
        run: make install

      # 5. Überprüfe Coding Standards (PHP_CodeSniffer)
      - name: Check Code Standards with PHPCS
        run: make phpcs

      # 6. PHPUnit Tests mit Coverage starten
      - name: Run PHPUnit Tests with Coverage
        run: make phpunit-coverage

      # 7. Statische Codeanalyse ausführen
      - name: Run PHPStan (Static Analysis)
        run: make phpstan

      # 8. Docker Umgebung herunterfahren, falls erforderlich
      - name: Tear Down Docker Environment
        if: always()
        run: make remove
